local Message = {
        muted   =   "咱吃糖去了  [MUTE]"
    ,   unmuted =   "咱能开腔啦~"
    ,   auto_muted  =   "咱累了 [MUTE]"
    ,   ignore  =   "咱才不理你呢 ´ ▽ ` )ﾉ"
    ,   uploading   =   "空中下载开始~ 咱在整理哦~ (✪㉨✪)"
    ,   deploy_fail =   "## 错误 ## 部署失败"
    ,   auth_pass   =   "是授权用户哦(・∀・)"
    ,   auth_fail   =   "还不是授权用户哦(･ｪ-)"
    ,   not_allow   =   "人家才不听你的嘞 ╮(￣▽￣)╭"
    ,   not_allow2  =   "不听不听 和尚念经"
    ,   help        =   [[小Bot V-{Version}, 帮助文档: .lua code => 将执行code 等同于load(code)(), 会将结果直接输出到频道, print注册为无指向频道信息 .reload => 将重新加载机器人, 同时刷新每个人的环境]]
    ,   say_help    =   ":say 想被重复的话=> bot会重复说这句话哦"
    ,   sm_help     =   ":sm {nick} {给他/她贴的标签啦}"
    ,   sm_dupl     =   "这个标签已经存在啦(◕‿◕✿) 换一个嘛(￣□￣)"
    ,   sm_lost     =   "没有找到标签哦! 快贴几个啦(・∀・)"
    ,   reject_bot  =   "me ●REC o(///▽///)q 抓到一只BOT"
    ,   reject_say  =   "过分啦~~(￣□￣) 人家不是话痨"
    ,   leak_say    =   "好吧 好吧 偷偷告诉你啦: ╮(￣▽￣)╭ "
    ,   last_help   =   ".last {name} => 显示出bot记录的这个用户最后一次发言"
    ,   last_lost   =   "[%s]说啥? 咱不知道唉"
    ,   last_nil    =   "神秘人"
    ,   last_say    =   "[%s]@[%s] 喵了句 %s"
    ,   query_say   =   "喵了些:"
    ,   query_help  =   "查询某个用户说过的话, 可以特定查询, 或者列出最后几句话"
    ,   query_error =   "¯\\_(ツ)_/¯出错啦~ 手写的垃圾数据库挂咯"
    ,   query_lost  =   "告诉咱是谁啦~"
}
return Message
